apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: invint
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - investor-ai-platform.site
    secretName: invint-tls

  rules:
  - host: investor-ai-platform.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: invint
            port:
              number: 80
